import type { Metadata } from "next";
import Link from "next/link";
import { PhoneLink } from "@/components/phone-link";
import { ELECTRICIAN_PAGES, ELECTRICIAN_SERVICES, getPagesByService } from "@/lib/electrician-data";
import { EMERGENCY_PHONE_DISPLAY, SITE_NAME, absoluteUrl } from "@/lib/seo";

export const metadata: Metadata = { title: "Electrical Services Canada Directory", description: "Browse The Duo Electrician service pages for local electricians, emergency help, residential service, commercial electrical work, and repairs across Canada.", alternates: { canonical: "/services" }, openGraph: { title: `Electrical Services Across Canada | ${SITE_NAME}`, description: "Complete service and city directory for The Duo Electrician.", url: absoluteUrl("/services"), type: "website", siteName: SITE_NAME } };

export default function ServicesPage() {
  return <main className="tde-shell"><section className="tde-index-hero"><div className="tde-container tde-index-hero-grid"><div><p className="tde-kicker">Services</p><h1>Choose the electrical service path, then choose the local page.</h1></div><div><p>This directory connects national hubs, service hubs, modifier pages, and city landing pages so every generated page receives internal links and visitors always have a next step.</p><PhoneLink className="tde-btn tde-btn-primary" location="services-hero" pageTier="services">Call {EMERGENCY_PHONE_DISPLAY}</PhoneLink></div></div></section><section className="tde-directory-section"><div className="tde-container tde-service-directory">{ELECTRICIAN_SERVICES.map((service)=>{ const pages=getPagesByService(service.slug); return <article key={service.slug} className="tde-directory-row"><div><p className="tde-kicker">{pages.length} pages</p><h2>{service.name}</h2><p>{service.intro}</p><Link href={`/services/${service.slug}`} className="tde-text-link">Open {service.name} pillar</Link></div><div className="tde-mini-link-grid">{pages.map((page)=><Link key={page.slug} href={`/${page.slug}`}>{page.primaryKeyword}</Link>)}</div></article>})}</div></section><section className="tde-all-pages-section"><div className="tde-container"><div className="tde-section-head compact"><p className="tde-kicker">Full directory</p><h2>All generated pages are linked here.</h2></div><div className="tde-all-page-grid">{ELECTRICIAN_PAGES.map((page)=><Link key={page.slug} href={`/${page.slug}`}>{page.title.replace(/\s*\|.*$/, "")}</Link>)}</div></div></section></main>;
}
